OffsetDateProvider Class to reduce the likelihood of "request timestamp expired" exceptions.
rotiv123/GdaxApi pull request #5
Opened 2018-04-19 18:58 UTC by PiezPiedPy

Allows the client time to more closely match the GDAX API web servers time, reducing the likelihood of "request timestamp expired" exceptions due to small time discrepancies.

Depending on the time of day, I was receiving "request timestamp expired" exceptions when trying to communicate with the GDAX web server, after checking many times the synchronization of my clock with my local GMT time and finding no difference, I started troubleshooting and found that the problem was due to small time discrepancies between the GDAX web server and my local time, that would slowly increment throughout the day before dropping back down to zero and repeating the cycle.
The offset can get up to 90+ seconds and with the maximum offset of 30 seconds allowed by the GDAX web server I would start receiving the "request timestamp expired" exception.

Here is an example output of the offset when the exceptions started to appear, notice it is just above 30 seconds.
`GdaxTimeOffset: Local UTC Time   19/04/2018 5:52:45 pm +00:00`
`GdaxTimeOffset: GDAX Server Time 19/04/2018 5:53:16 pm +00:00`
`GdaxTimeOffset: Timestamp offset -31.593466758728`

The `OffsetDateProvider` Class I have created obtains the GDAX webserver time and calculates the difference from Local time and stores it for use by the `GdaxAuthenticationHandler` Class.
Time synchronization is not automatic and must be manually updated, it is refreshed by the user through the use of the method `RealOffset`.
If this method is never called by the user then the stored offset will remain at Zero and the `GdaxAuthenticationHandler` will operate as in previous releases. 

Since implementing this Time Offset class I have had no more issues with the "request timestamp expired" exception rearing its ugly head.

I have also enabled the building of the XML documentation file which is automatically included by Visual Studio into the NuGet package when Publishing is performed, allowing end users to view the summaries with Intelisense on Visual Studio.

2018-04-22 16:44 UTC, rotiv123 requested changes
Refactor your changes into a class that implements the IDateProvider interface.

2018-04-22 20:33 UTC, PiezPiedPy commented
Is there a way the InnerHandler can be set in the GdaxApiClient class rather than the user having to set it.
I think it would be better to be able to use code such as:

`authenticator = new GdaxAuthenticationHandler(gdax_credentials, date_provider);`

rather than having to use:

`authenticator = new GdaxAuthenticationHandler(gdax_credentials, date_provider) { InnerHandler = new HttpClientHandler() };`

Must be a way but I cant see it, I will have a think tomorrow after some sleep 🛌

2018-04-23 18:59 UTC, rotiv123 requested changes

2018-04-23 18:59 UTC, rotiv123 commented on src/GdaxApi/GdaxApi/GdaxApi.csproj
> +    <NoWarn>1701;1702;1705;1591</NoWarn>
Why disable this warnings: 1701;1702;1705?

2018-04-23 18:59 UTC, rotiv123 commented on src/GdaxApi/GdaxApi/GdaxApiClient.cs
> +                authenticationHandler.InnerHandler = new HttpClientHandler();
missing {}

2018-04-23 18:59 UTC, rotiv123 commented on src/GdaxApi/GdaxApi/Utils/OffsetDateProvider.cs
> +        public async Task<double> RealOffset(GdaxApiClient api, bool refresh = false)
Whats the point of calling this method to get the API server time?
This method should receive directly an "ApiTime" and update its internal offset. That way there is no need to use the "refresh" parameter.

2018-04-23 18:59 UTC, rotiv123 commented on src/GdaxApi/GdaxApi/Utils/OffsetDateProvider.cs
> +            catch { throw; }
No useless catch statements please

2018-04-23 18:59 UTC, rotiv123 commented on src/GdaxApi/GdaxApi/Utils/OffsetDateProvider.cs
> +        public DateTimeOffset Now => DateTimeOffset.Now;
This property must represent the same date as the "UnixTimestamp" property, apart from the timezone offset. You forgot to subtract the "StoredOffset"

2018-04-23 20:55 UTC, PiezPiedPy commented on src/GdaxApi/GdaxApi/GdaxApi.csproj
> +    <NoWarn>1701;1702;1705;1591</NoWarn>
They where previously defined, I did not add them. I only added the 1591 warning

2018-04-23 21:01 UTC, PiezPiedPy commented on src/GdaxApi/GdaxApi/GdaxApiClient.cs
> +                authenticationHandler.InnerHandler = new HttpClientHandler();
Didn't know they where required, works in testing, I'll add them

2018-04-23 21:08 UTC, PiezPiedPy commented on src/GdaxApi/GdaxApi/Utils/OffsetDateProvider.cs
> +        public DateTimeOffset Now => DateTimeOffset.Now;
Ok, I'll add in the offset

2018-04-23 21:12 UTC, PiezPiedPy commented on src/GdaxApi/GdaxApi/Utils/OffsetDateProvider.cs
> +        public async Task<double> RealOffset(GdaxApiClient api, bool refresh = false)
Idea is to save calling the GDAX webserver repeatedly and only use the refresh when needed. i.e. only refresh when the time offset gets close to 30 seconds. 
I could add a bool property so the end user can set the class to an automatic or manual refresh mode.
btw, do you think automatic if implemented, refreshes the offset before each call to the GDAX webserver or use a timer that waits till the offset gets close to 30 seconds before refreshing?

2018-04-23 21:16 UTC, PiezPiedPy commented on src/GdaxApi/GdaxApi/Utils/OffsetDateProvider.cs
> +            catch { throw; }
I was throwing the exception back to the user to handle.
Any idea what exception I should throw, or should I remove the try catch all together? (removing seems a bad idea to me)

2018-04-25 10:53 UTC, rotiv123 requested changes

2018-04-25 10:53 UTC, rotiv123 commented on src/GdaxApi/GdaxApi/GdaxApi.csproj
> +    <NoWarn>1701;1702;1705;1591</NoWarn>
yes

2018-04-25 11:43 UTC, PiezPiedPy commented on src/GdaxApi/GdaxApi/GdaxApi.csproj
> +    <NoWarn>1701;1702;1705;1591</NoWarn>
Done 😉

2018-04-26 18:46 UTC, merged